apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: demo-app
spec:
  encryptedData:
    secret: AgBRt9f8aot1pIbTvUPj62mXj6GxSBTZq8HH5R5N8KjnxE/++ivXVLYZNr4PI3ZeEprCrNfbSYVfCwF0L257bK91G/hmjdgYOW6PmrDN9M97p/UIUrpSchzRKAxaKkbXV9+/uDJdNX8MLZIBuF/o2LkDilI0tuMHQTtVj7Of4JI9SHhNwdAZAwJqO9G41TPFmYgj62VkA3EThJGNHSBrKvxqrfLXMn0cLig4C/88yiqeI4UY7YBQEXcWEN5cIzWg+O7uVqMZKIOB88WtAx7EnVGXqtDcXW8w7HvfKEfrM3VWRu1uzG/CY4HfYv6w19ss1LwMTN/Jf7wnrSBBxp/KGY/WW3R4mUFxtdNR7hrfYgRDiRl6k1fMPdNlMf2df98YIRYFQAQlCQ3UL4WH8ya8VnQV4BClPMModobMEPBOwOcBeFBSWzkcCQwu6IFSVLAJM1B0OaWsLdd4pUdt7ak91B6r0ows9QEnowKxYq5q6TI6mDtENIUXBSb0enoD8RqgJZZUlWIb3Lqsh6BtUoeTIa9QYAneUPRg0hBBQ3I8dtl3F/mHWnj3XuxRjXUijh5vCRaLWPek+tiR+q7PxKM/KjL+czCh3CXqZDGk1NsRw+8+9dEWDOsLcXETB8i9T22b/CiA8Xn9cU1y3u0q2mE/h2uSqAtJ0Qy1Q2yRtbE90Kc6XQV6AJQkwATZrzdVxfqcL/7d8dzSZk1UVzHq0jo=
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: demo-app
---
